[package]
name = "ferrwm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
die = "0.2"
x11rb = { version = "0.9.0", features = [ "all-extensions" ] }
openbsd = "0.1.2"
